language: node_js
sudo: false
node_js:
  - "5.6"
  - "4.0"
services:
  - postgresql
addons:
  - postgresql: "9.3"
  - apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
before_script:
  - npm install -g knex
  - psql -c 'create database test;' -U postgres
  - npm run migrate