language: node_js
node_js:
  - "4"
services:
  - postgresql
addons:
  - postgresql: "9.3"
  - apt:
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - g++-4.8
env:
  - CXX=g++-4.8
before_script:
  - npm install -g knex
  - psql -c 'create database test;' -U postgres
  - npm run migrate