language: node_js
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
services:
  - postgresql
addons:
  - postgresql: "9.3"
before_script:
  - npm install -g knex
  - psql -c 'create database test;' -U postgres
  - npm run migrate